name: 'finetue'
description: 'github actions for OpenAI fine tuning'
inputs:
  openai-api-key:
    description: 'the OpenAI API key'
    required: true
    default: ''
  openai-api-org:
    description: 'the OpenAI org for your api'
    required: false
    default: ''
  dataset:  # id of input
    description: 'the path to dataset json file'
    required: true
    default: './dataset.json'
  dataset-wait-time:
    description: 'timewait for the dataset processed'
    required: false
    default: 300000 # 5min
  job-wait-time:
    description: 'timewait for the model trained'
    required: false
    default: 300000 # 5min
outputs:
  model:
    description: 'the model trained out'
  status: 
    description: 'the status of the fine tuning job'
runs: 
  using: 'node16'
  main: 'dist/index.js'
