name: 'check-dataset'
description: 'check dataset status'
inputs:
  openai-api-key:
    description: 'the OpenAI API key'
    required: true
    default: ''
  openai-api-org:
    description: 'the OpenAI org for your api'
    required: false
    default: ''
  file-id:  # id of input
    description: 'the id of the dataset file'
    required: true
    default: ''
outputs:
  status: # id of output
    description: 'the status of dataset'
runs:
  using: 'node16'
  main: 'dist/index.js'
