name: 'ci'
on:
  push:
    branches:
      - 'v*'
    tags:        
      - 'v*'
jobs:
  flow:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: fine tune
        id: finetune
        uses: ./
        with:
          dataset: './dataset.json'
          openai-api-key: ${{ secrets.OPEN_AI_KEY }}
          openai-api-org: ${{ secrets.OPEN_AI_ORG }}
          dataset-wait-time: 60000
          job-wait-time: 60000
      - name: use the model
        run: echo "The model is ${{ steps.finetune.outputs.model }} ${{ steps.finetune.outputs.status }}"
